import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
  alias(libs.plugins.android.library)
}

android {
  namespace "com.braze.unity"

  defaultConfig {
    compileSdk rootProject.ext.compileSdkVersion
    minSdkVersion rootProject.ext.minSdkVersion
    aarMetadata {
      minCompileSdk rootProject.ext.minSdkVersion
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

}

kotlin {
  compilerOptions {
    jvmDefault.set(JvmDefaultMode.NO_COMPATIBILITY)
    jvmTarget.set(JvmTarget.JVM_1_8)
  }
}

dependencies {
  compileOnly files("libs/Prime31UnityActivity-1.0.jar")
  compileOnly files("libs/unity-2019.2.12f1.jar")
  compileOnly libs.androidx.annotations
  implementation libs.kotlin.stdlib
  implementation project(':android-sdk-ui')
}
