{
  "formatVersion": "1.1",
  "component": {
    "group": "com.braze",
    "module": "braze-segment-kotlin",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "braze-segment-kotlin-1.4.1.aar",
          "url": "braze-segment-kotlin-1.4.1.aar",
          "size": 19515,
          "sha512": "69b91fbeb5a92997e4492fd9f8cccdbc85c14ce93d6db4d5e91880bdd3b908277fae2a47484a7a94c123b5c3dfc0d610c087b45dacc0e69901183702a3443461",
          "sha256": "36dad95414a29d18678b2fb8f4671ba106c7430e7d989366b4a33b963b0137c7",
          "sha1": "25d301db66b6cbff36d10fdf143de9fd87a69c6d",
          "md5": "f58a95cffb00fd880c94b7ecf98236d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.braze",
          "module": "android-sdk-ui",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "com.segment.analytics.kotlin",
          "module": "android",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "braze-segment-kotlin-1.4.1.aar",
          "url": "braze-segment-kotlin-1.4.1.aar",
          "size": 19515,
          "sha512": "69b91fbeb5a92997e4492fd9f8cccdbc85c14ce93d6db4d5e91880bdd3b908277fae2a47484a7a94c123b5c3dfc0d610c087b45dacc0e69901183702a3443461",
          "sha256": "36dad95414a29d18678b2fb8f4671ba106c7430e7d989366b4a33b963b0137c7",
          "sha1": "25d301db66b6cbff36d10fdf143de9fd87a69c6d",
          "md5": "f58a95cffb00fd880c94b7ecf98236d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "braze-segment-kotlin-1.4.1-sources.jar",
          "url": "braze-segment-kotlin-1.4.1-sources.jar",
          "size": 5359,
          "sha512": "28987e1727cf7548001cd31822564e85f7605c096433d648c2ea542a77fee3d42914f0576515aaea116b565cf30d00be66f63f0d91ebe4363b86c12b6b17d43f",
          "sha256": "6a0f6887f7838545bf3fe785118fea78e58ea534105589190e5fe1c189bcc042",
          "sha1": "f1464531962cc61b81d7726311bf481517277228",
          "md5": "95bed4d233d22597623972a8f76c2dfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "braze-segment-kotlin-1.4.1-javadoc.jar",
          "url": "braze-segment-kotlin-1.4.1-javadoc.jar",
          "size": 290560,
          "sha512": "382a40d86444ede4eb1c8d408a6965f7dd9c8077d09bc11b22733674e73dc25dac09092317fe13b5f99d50e0c21af8532e2ccbedb58d3e4eb1833e26bfaf8b3f",
          "sha256": "b5655c3ef72c20e1669626c30b9d9927c6f779190ccfd133c83a6ffaf3f94d55",
          "sha1": "6bd8795d149bfaaa997b900827a33a2003f929a9",
          "md5": "9e12aff7ab8fe72e09d8c76e76996eec"
        }
      ]
    }
  ]
}
