import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
  alias(libs.plugins.android.library)
}

android {
  namespace "com.braze.ui"

  defaultConfig {
    compileSdk rootProject.ext.compileSdkVersion
    minSdkVersion rootProject.ext.minSdkVersion
    consumerProguardFiles 'braze-consumer-proguard-rules.pro'
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

}

kotlin {
  compilerOptions {
    jvmDefault.set(JvmDefaultMode.NO_COMPATIBILITY)
    jvmTarget.set(JvmTarget.JVM_1_8)
  }
}

dependencies {
  api "com.braze:android-sdk-base:${BRAZE_SDK_VERSION}"
  compileOnly libs.google.material

  implementation libs.kotlin.coroutines.android
  implementation libs.androidx.core
  implementation libs.androidx.fragment
  implementation libs.androidx.recyclerview
  implementation libs.androidx.swiperefreshlayout
  implementation libs.androidx.webkit

  // Required for the FirebaseMessagingService
  compileOnly libs.firebase.messaging
}
